/*
JV-Data仕様書

*/

// RecordTypes（レコード種別）の定義
type RecordTypesType = {
    [RecordTypeID: string]: {
        recordTypeID: string;
        formatNumber: number;
        recordSize: number;
        recordName: string;
    },
};
export const RecordTypes: RecordTypesType = {
    "AV": {"recordTypeID": "AV", "formatNumber": 103, "recordSize": 78, "recordName": "出走取消・競走除外"},
    "BN": {"recordTypeID": "BN", "formatNumber": 17, "recordSize": 477, "recordName": "馬主マスタ"},
    "BR": {"recordTypeID": "BR", "formatNumber": 16, "recordSize": 545, "recordName": "生産者マスタ"},
    "BT": {"recordTypeID": "BT", "formatNumber": 26, "recordSize": 6889, "recordName": "系統情報"},
    "CC": {"recordTypeID": "CC", "formatNumber": 106, "recordSize": 50, "recordName": "コース変更"},
    "CH": {"recordTypeID": "CH", "formatNumber": 15, "recordSize": 3862, "recordName": "調教師マスタ"},
    "CK": {"recordTypeID": "CK", "formatNumber": 20, "recordSize": 6870, "recordName": "出走別着度数"},
    "CS": {"recordTypeID": "CS", "formatNumber": 27, "recordSize": 6829, "recordName": "コース情報"},
    "DM": {"recordTypeID": "DM", "formatNumber": 28, "recordSize": 303, "recordName": "タイム型データマイニング予想"},
    "H1": {"recordTypeID": "H1", "formatNumber": 5, "recordSize": 28955, "recordName": "票数１"},
    "H6": {"recordTypeID": "H6", "formatNumber": 6, "recordSize": 102890, "recordName": "票数6（3連単）"},
    "HC": {"recordTypeID": "HC", "formatNumber": 22, "recordSize": 60, "recordName": "坂路調教"},
    "HN": {"recordTypeID": "HN", "formatNumber": 18, "recordSize": 251, "recordName": "繁殖馬マスタ"},
    "HR": {"recordTypeID": "HR", "formatNumber": 4, "recordSize": 719, "recordName": "払戻"},
    "HS": {"recordTypeID": "HS", "formatNumber": 23, "recordSize": 200, "recordName": "競走馬市場取引価格"},
    "HY": {"recordTypeID": "HY", "formatNumber": 24, "recordSize": 123, "recordName": "馬名の意味由来"},
    "JC": {"recordTypeID": "JC", "formatNumber": 104, "recordSize": 161, "recordName": "騎手変更"},
    "JG": {"recordTypeID": "JG", "formatNumber": 31, "recordSize": 80, "recordName": "競走馬除外情報"},
    "KS": {"recordTypeID": "KS", "formatNumber": 14, "recordSize": 4173, "recordName": "騎手マスタ"},
    "O1": {"recordTypeID": "O1", "formatNumber": 7, "recordSize": 962, "recordName": "オッズ1（単複枠）"},
    "O2": {"recordTypeID": "O2", "formatNumber": 8, "recordSize": 2042, "recordName": "オッズ2（馬連）"},
    "O3": {"recordTypeID": "O3", "formatNumber": 9, "recordSize": 2654, "recordName": "オッズ3（ワイド）"},
    "O4": {"recordTypeID": "O4", "formatNumber": 10, "recordSize": 4031, "recordName": "オッズ4（馬単）"},
    "O5": {"recordTypeID": "O5", "formatNumber": 11, "recordSize": 12293, "recordName": "オッズ5（3連複）"},
    "O6": {"recordTypeID": "O6", "formatNumber": 12, "recordSize": 83285, "recordName": "オッズ6（3連単）"},
    "RA": {"recordTypeID": "RA", "formatNumber": 2, "recordSize": 1272, "recordName": "レース詳細"},
    "RC": {"recordTypeID": "RC", "formatNumber": 21, "recordSize": 501, "recordName": "レコードマスタ"},
    "SE": {"recordTypeID": "SE", "formatNumber": 3, "recordSize": 555, "recordName": "馬毎レース情報"},
    "SK": {"recordTypeID": "SK", "formatNumber": 19, "recordSize": 208, "recordName": "産駒マスタ"},
    "TC": {"recordTypeID": "TC", "formatNumber": 105, "recordSize": 45, "recordName": "発走時刻変更"},
    "TK": {"recordTypeID": "TK", "formatNumber": 1, "recordSize": 21657, "recordName": "特別登録馬"},
    "TM": {"recordTypeID": "TM", "formatNumber": 29, "recordSize": 141, "recordName": "対戦型データマイニング予想"},
    "UM": {"recordTypeID": "UM", "formatNumber": 13, "recordSize": 1609, "recordName": "競走馬マスタ"},
    "WC": {"recordTypeID": "WC", "formatNumber": 32, "recordSize": 105, "recordName": "ウッドチップ調教"},
    "WE": {"recordTypeID": "WE", "formatNumber": 102, "recordSize": 42, "recordName": "天候馬場状態"},
    "WF": {"recordTypeID": "WF", "formatNumber": 30, "recordSize": 7215, "recordName": "重勝式(WIN5)"},
    "WH": {"recordTypeID": "WH", "formatNumber": 101, "recordSize": 847, "recordName": "馬体重"},
    "YS": {"recordTypeID": "YS", "formatNumber": 25, "recordSize": 382, "recordName": "開催スケジュール"},
};

// DataSpecs（データ種別）の定義
type DataSpecs = {
    [DataType: string]: {
        [DataSpecName: string]: string[];   // DataSpecNameに対するRecordTypeIDのリスト
    },
}
export const DataSpecs: DataSpecs = {
    "Accumulated": {
        "TOKU": ["TK"],
        "RACE": [
            "RA",
            "SE",
            "HR",
            "H1",
            "H6",
            "O1",
            "O2",
            "O3",
            "O4",
            "O5",
            "O6",
            "WF",
            "JG",
        ],
        "DIFF": [
            "UM",
            "KS",
            "CH",
            "BR",
            "BN",
            "RC",
            "RA",
            "SE",
        ],
        "DIFN": [
            "UM",
            "KS",
            "CH",
            "BR",
            "BN",
            "RC",
            "RA",
            "SE",
        ],
        "BLOD": [
            "HN",
            "SK",
            "BT",
        ],
        "BLDN": [
            "HN",
            "SK",
            "BT",
        ],
        "MING": [
            "DM",
            "TM",
        ],
        "SNAP": ["CK"],
        "SNPN": ["CK"],
        "SLOP": ["HC"],
        "YSCH": ["YS"],
        "HOSE": ["HS"],
        "HOSN": ["HS"],
        "HOYU": ["HY"],
        "COMM": ["CS"],
        "WOOD": ["WC"],
        "TCOV": [
            "UM",
            "CH",
            "BR",
            "BN",
            "RC",
            "RA",
            "SE",
        ],
        "TCVN": [
            "UM",
            "CH",
            "BR",
            "BN",
            "RC",
            "RA",
            "SE",
        ],
        "RCOV": [
            "UM",
            "KS",
            "CH",
            "BR",
            "BN",
            "RC",
            "RA",
            "SE",
        ],
        "RCVN": [
            "UM",
            "KS",
            "CH",
            "BR",
            "BN",
            "RC",
            "RA",
            "SE",
        ],
    },
    "Realtime": {
        "0B12": [
            "RA",
		    "SE",
		    "HR",
        ],
        "0B15": [
            "RA",
		    "SE",
		    "HR",
        ],
        "0B30": [
            "O1",
		    "O2",
		    "O3",
		    "O4",
		    "O5",
		    "O6",
        ],
        "0B31": ["O1"],
        "0B32": ["O2"],
        "0B33": ["O3"],
        "0B34": ["O4"],
        "0B35": ["O5"],
        "0B36": ["O6"],
        "0B20": [
            "H1",
            "H6",
        ],
        "0B11": ["WH"],
        "0B14": [
            "WE",
            "AV",
            "JC",
            "TC",
            "CC",
        ],
        "0B16": [
            "WE",
		    "AV",
		    "JC",
		    "TC",
		    "CC",
        ],
        "0B13": ["DM"],
        "0B17": ["TM"],
        "0B41": ["O1"],
        "0B42": ["O2"],
        "0B51": ["WF"],
    },
    "Setup": {
        "RACE": [
            "RA",
            "SE",
            "HR",
            "H1",
            "H6",
            "O1",
            "O2",
            "O3",
            "O4",
            "O5",
            "O6",
            "WF",
            "JG",
        ],
        "DIFF": [
    	    "UM",
		    "KS",
		    "CH",
		    "BR",
		    "BN",
		    "RC",
        ],
        "DIFN": [
    	    "UM",
		    "KS",
		    "CH",
		    "BR",
		    "BN",
		    "RC",
        ],
        "BLOD": [
            "HN",
            "SK",
            "BT",
        ],
        "BLDN": [
            "HN",
            "SK",
            "BT",
        ],
        "MING": [
            "DM",
		    "TM",
        ],
        "SNAP": ["CK"],
        "SNPN": ["CK"],
        "SLOP": ["HC"],
        "YSCH": ["YS"],
        "HOSE": ["HS"],
        "HOSN": ["HS"],
        "HOYU": ["HY"],
        "COMM": ["CS"],
        "WOOD": ["WC"],
    },
};
