-- レース詳細
CREATE TABLE RaceDetail (
    dataCategory TEXT NULL,
    creationDate TEXT NULL,
    eventYear TEXT NULL,
    eventMonthDay TEXT NULL,
    raceCourseCode TEXT NULL,
    eventRound INTEGER NULL,
    eventDay INTEGER NULL,
    raceNumber INTEGER NULL,
    weekdayCode TEXT NULL,
    specialRaceNumber TEXT NOT NULL,
    raceName TEXT NOT NULL,
    raceNameSub TEXT NOT NULL,
    raceNameParentheses TEXT NOT NULL,
    raceNameEng TEXT NOT NULL,
    raceNameSubEng TEXT NOT NULL,
    raceNameParenthesesEng TEXT NOT NULL,
    raceNameAbbr10 TEXT NOT NULL,
    raceNameAbbr6 TEXT NOT NULL,
    raceNameAbbr3 TEXT NOT NULL,
    raceTitleCategory TEXT NOT NULL,
    gradeCount INTEGER NOT NULL,
    gradeCode TEXT NOT NULL,
    previousGradeCode TEXT NOT NULL,
    raceTypeCode TEXT NULL,
    raceSymbolCode TEXT NULL,
    weightTypeCode TEXT NULL,
    raceConditionCode2YearOld TEXT NOT NULL,
    raceConditionCode3YearOld TEXT NOT NULL,
    raceConditionCode4YearOld TEXT NOT NULL,
    raceConditionCode5YearOldAndAbove TEXT NOT NULL,
    raceConditionCodeYoungest TEXT NOT NULL,
    raceConditionName TEXT NOT NULL,
    distance INTEGER NULL,
    previousDistance INTEGER NOT NULL,
    trackCode TEXT NULL,
    previousTrackCode TEXT NOT NULL,
    courseCategory TEXT NOT NULL,
    previousCourseCategory TEXT NOT NULL,
    mainPrizeMoney_1 INTEGER NOT NULL,
    mainPrizeMoney_2 INTEGER NOT NULL,
    mainPrizeMoney_3 INTEGER NOT NULL,
    mainPrizeMoney_4 INTEGER NOT NULL,
    mainPrizeMoney_5 INTEGER NOT NULL,
    mainPrizeMoney_6 INTEGER NOT NULL,
    mainPrizeMoney_7 INTEGER NOT NULL,
    previousPrizeMoney_1 INTEGER NOT NULL,
    previousPrizeMoney_2 INTEGER NOT NULL,
    previousPrizeMoney_3 INTEGER NOT NULL,
    previousPrizeMoney_4 INTEGER NOT NULL,
    previousPrizeMoney_5 INTEGER NOT NULL,
    additionalPrizeMoney_1 INTEGER NOT NULL,
    additionalPrizeMoney_2 INTEGER NOT NULL,
    additionalPrizeMoney_3 INTEGER NOT NULL,
    additionalPrizeMoney_4 INTEGER NOT NULL,
    additionalPrizeMoney_5 INTEGER NOT NULL,
    previousAdditionalPrizeMoney_1 INTEGER NOT NULL,
    previousAdditionalPrizeMoney_2 INTEGER NOT NULL,
    previousAdditionalPrizeMoney_3 INTEGER NOT NULL,
    startTime TEXT NULL,
    previousStartTime TEXT NOT NULL,
    registeredHorsesCount INTEGER NULL,
    numberOfRunners INTEGER NOT NULL,
    horsesFinishedCount INTEGER NOT NULL,
    weatherCode TEXT NOT NULL,
    turfConditionCode TEXT NOT NULL,
    dirtConditionCode TEXT NOT NULL,
    lapTime_1 REAL NOT NULL,
    lapTime_2 REAL NOT NULL,
    lapTime_3 REAL NOT NULL,
    lapTime_4 REAL NOT NULL,
    lapTime_5 REAL NOT NULL,
    lapTime_6 REAL NOT NULL,
    lapTime_7 REAL NOT NULL,
    lapTime_8 REAL NOT NULL,
    lapTime_9 REAL NOT NULL,
    lapTime_10 REAL NOT NULL,
    lapTime_11 REAL NOT NULL,
    lapTime_12 REAL NOT NULL,
    lapTime_13 REAL NOT NULL,
    lapTime_14 REAL NOT NULL,
    lapTime_15 REAL NOT NULL,
    lapTime_16 REAL NOT NULL,
    lapTime_17 REAL NOT NULL,
    lapTime_18 REAL NOT NULL,
    lapTime_19 REAL NOT NULL,
    lapTime_20 REAL NOT NULL,
    lapTime_21 REAL NOT NULL,
    lapTime_22 REAL NOT NULL,
    lapTime_23 REAL NOT NULL,
    lapTime_24 REAL NOT NULL,
    lapTime_25 REAL NOT NULL,
    obstacleMileTime REAL NOT NULL,
    first3Furlongs REAL NOT NULL,
    first4Furlongs REAL NOT NULL,
    last3Furlongs REAL NOT NULL,
    last4Furlongs REAL NOT NULL,
    CornerPassingOrder_1_corner TEXT NOT NULL,
    CornerPassingOrder_1_lapNumber TEXT NOT NULL,
    CornerPassingOrder_1_individualPassingOrder TEXT NOT NULL,
    CornerPassingOrder_2_corner TEXT NOT NULL,
    CornerPassingOrder_2_lapNumber TEXT NOT NULL,
    CornerPassingOrder_2_individualPassingOrder TEXT NOT NULL,
    CornerPassingOrder_3_corner TEXT NOT NULL,
    CornerPassingOrder_3_lapNumber TEXT NOT NULL,
    CornerPassingOrder_3_individualPassingOrder TEXT NOT NULL,
    CornerPassingOrder_4_corner TEXT NOT NULL,
    CornerPassingOrder_4_lapNumber TEXT NOT NULL,
    CornerPassingOrder_4_individualPassingOrder TEXT NOT NULL,
    recordUpdateCategory TEXT NOT NULL
);
