-- 特別登録馬
CREATE TABLE SpecialRegisteredHorses (
    dataCategory TEXT NULL,
    creationDate TEXT NULL,
    eventYear TEXT NULL,
    eventMonthDay TEXT NULL,
    raceCourseCode TEXT NULL,
    eventRound INTEGER NULL,
    eventDay INTEGER NULL,
    raceNumber INTEGER NULL,
    weekdayCode TEXT NULL,
    specialRaceNumber TEXT NOT NULL,
    raceName TEXT NOT NULL,
    raceNameSub TEXT NOT NULL,
    raceNameParentheses TEXT NOT NULL,
    raceNameEng TEXT NOT NULL,
    raceNameSubEng TEXT NOT NULL,
    raceNameParenthesesEng TEXT NOT NULL,
    raceNameAbbr10 TEXT NOT NULL,
    raceNameAbbr6 TEXT NOT NULL,
    raceNameAbbr3 TEXT NOT NULL,
    raceTitleCategory TEXT NOT NULL,
    gradeCount INTEGER NOT NULL,
    gradeCode TEXT NOT NULL,
    raceTypeCode TEXT NULL,
    raceSymbolCode TEXT NULL,
    weightTypeCode TEXT NULL,
    raceConditionCode2YearOld TEXT NOT NULL,
    raceConditionCode3YearOld TEXT NOT NULL,
    raceConditionCode4YearOld TEXT NOT NULL,
    raceConditionCode5YearOldAndAbove TEXT NOT NULL,
    raceConditionCodeYoungest TEXT NOT NULL,
    distance INTEGER NULL,
    trackCode TEXT NULL,
    courseCategory TEXT NOT NULL,
    handicapAnnouncementDate TEXT NOT NULL,
    registeredHorsesCount INTEGER NULL
);
